### ISSUE TITLE
peoblem

### ISSUE THREAD

**Issue by Jigsaw855** [foxlox/GIUDA#1]
hello 
thanks for your great tools 
I tested it and got CIFS service ticket then I connected to \\DC\C$ directory and copied file but when I wanted to connect to DC with PS exec , I got access denied error . and after a few minute cife ticket not properly work and I was forced reimported ticket even it  worked correctly too do you have any idea about this ?
I tested Host service ticket and created  Schedule task on DC . that worked correctly 
*the important point in this tool is that you should use FQDN instead of IP

**Comment by foxlox** [comment]
Kerberos needs fqdn, because if you use IP, authentication falls back to MSV1_0.

To use PSEXEC you need also HOST

Try HTTP to use pssession it's more stealth
