### ISSUE TITLE
Detected by Defender

### ISSUE THREAD

**Issue by jsdhasfedssad** [foxlox/GIUDA#2]
Hi,

This tool looks good. However, when executing `.\giuda.exe -gettgs -luid:0x[LUID] -msdsspn:http/dc1`, Defender detects this. If `Enter-PSSession -ComputerName dc1` is attempted afterwards this results in the error "Processing data from remote server dc1 failed with the following error message: WinRM cannot process the request. The following error with errorcode 0x8009030e occurred while using Kerberos authentication: A specified logon session does not exist. It may already have been terminated".

**Comment by foxlox** [comment]
Did you download the latest? Post a screenshot. Thx

**Comment by jsdhasfedssad** [comment]
I downloaded the binary yesterday, my time of course. That seem to be the latest release.

My test scenario is as follows. I have local admin access to server1 on which domainadmin1 is logged on. On server3, which typically would be a client's workstation/laptop or my own Windows VM in the real world, I execute runas and authenticate using the local admin credentials on server1. In the new shell I first copy giuda.exe to server1 then I execute psexec with the "-s" parameter in order to get a shell as SYSTEM on server1. In the SYSTEM shell I then use Giuda as instructed until Defender aborts it.  My guess is that when Giuda attempts to pass the TGS into memory on server1 that triggers Defender. Defender logs this as "Behavior:Win32/Mimikatz.O" which seems to fit in with the PTT.

<img width="1173" alt="tgs2" src="https://github.com/foxlox/GIUDA/assets/97032878/e7877737-c26b-4385-ae02-186532190572">

**Comment by jsdhasfedssad** [comment]
Even if I disable Defender on server1, which I can do as local admin, using winrs fails. Note that I first check that WinRM is setup properly on dc1.adlab.local. If I execute winrs directly on server1 logged in as domainadmin1 it works. I get a shell on dc1.adlab.local.

<img width="687" alt="tgs3" src="https://github.com/foxlox/GIUDA/assets/97032878/981c110d-e849-4ccf-950e-7153a92b9983">

**Comment by jsdhasfedssad** [comment]
In addition, I sometimes have issues with listing LUIDs. At the moment I do not know what is triggering this...
<img width="323" alt="tgs4png" src="https://github.com/foxlox/GIUDA/assets/97032878/07629601-1918-4bfb-a80a-62af070cfa24">

**Comment by foxlox** [comment]
> Even if I disable Defender on server1, which I can do as local admin, using winrs fails. Note that I first check that WinRM is setup properly on dc1.adlab.local. If I execute winrs directly on server1 logged in as domainadmin1 it works. I get a shell on dc1.adlab.local.
> <img alt="tgs3" width="687" src="https://private-user-images.githubusercontent.com/97032878/271821380-981c110d-e849-4ccf-950e-7153a92b9983.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjA0NjEsIm5iZiI6MTcwMzMyMDE2MSwicGF0aCI6Ii85NzAzMjg3OC8yNzE4MjEzODAtOTgxYzExMGQtZTg0OS00Y2NmLTk1MGUtNzE1M2E5MmI5OTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDA4MjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOTJmMTRiN2IyY2ZhNjhmYmQ0MDFjY2Y5MDZhOTJhNDg2NDJmMDE3MTkyOTc5Y2ZiYWY0ZWFhNGNkODUwN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fv6Rur2usN8vb4n4I2GKFLqmV-0YKwuBsAWNSolK40I">

Are you sure that you can use winrm with HOST spn?

**Comment by foxlox** [comment]
> In addition, I sometimes have issues with listing LUIDs. At the moment I do not know what is triggering this... <img alt="tgs4png" width="323" src="https://private-user-images.githubusercontent.com/97032878/271835963-07629601-1918-4bfb-a80a-62af070cfa24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzMjA0NjEsIm5iZiI6MTcwMzMyMDE2MSwicGF0aCI6Ii85NzAzMjg3OC8yNzE4MzU5NjMtMDc2Mjk2MDEtMTkxOC00YmZiLWE4MGEtNjJhZjA3MGNmYTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDA4MjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YzVkOTA2NDU4NzVhOTM0ZTI0NDIxNzhhZGQyMjM2MGVhZmI4ZjNiYWMwZjc2MDQ2ZDg0NDkyZjMyZDUxYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y1MUhinfAfQGq3OrZvS_3E07QHi_3GJk1jHSWSNkdFU">

you can get the same result with: klist sessions

**Comment by foxlox** [comment]
BTW use the latest release
